services:
 postgres:
   image: pgvector/pgvector:pg17
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - .env
     - .env.docker

 ragkit:
   build: .
   ports:
     - "8000:8000"
   depends_on:
     - postgres
   env_file:
     - .env
     - .env.docker
   volumes:
      - .:/app
   extra_hosts:
        - "host.docker.internal:host-gateway"
volumes:
  postgres_data: