# Generated by Django 6.0.7 on 2026-07-18 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ragkit', '0003_rename_qa_qaembedding_qa_foreign_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askedquestion',
            name='is_helpful',
        ),
        migrations.RemoveField(
            model_name='askedquestion',
            name='user',
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='chat uuid')),
                ('provider', models.CharField(max_length=50, verbose_name='Provider')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='askedquestion',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='django_ragkit.chat', verbose_name='Chat'),
        ),
        migrations.CreateModel(
            name='GeneratedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(blank=True, null=True, verbose_name='Is Helpful')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('replied_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_answer', to='django_ragkit.askedquestion', verbose_name='Replied Question')),
            ],
            options={
                'verbose_name': 'Generated Answer',
                'verbose_name_plural': 'Generated Answers',
                'ordering': ['-created_at'],
            },
        ),
    ]
