# Generated by Django 6.0.7 on 2026-07-20 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ragkit', '0004_remove_askedquestion_is_helpful_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askedquestion',
            name='similarity_rate',
        ),
        migrations.AddField(
            model_name='askedquestion',
            name='similarity_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Max Similarity Percentage'),
        ),
        migrations.AlterField(
            model_name='askedquestion',
            name='similar_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_ragkit.questionanswer', verbose_name='Most Similar Question'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='chat uuid'),
        ),
    ]
