# Generated by Django 6.0.7 on 2026-07-20 20:07

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ragkit', '0005_remove_askedquestion_similarity_rate_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='qaembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector'], m=16, name='qa_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
