# Generated by Django 6.0.7 on 2026-09-09 15:06

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ragkit', '0006_qaembedding_qa_embedding_hnsw_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaembedding',
            name='vector',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
    ]
