# Generated by Django 6.0.7 on 2026-09-09 15:47

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ragkit', '0008_alter_qaembedding_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaembedding',
            name='vector',
            field=pgvector.django.vector.VectorField(dimensions=1024),
        ),
    ]
