# Generated by Django 6.0.7 on 2026-07-18 13:29

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        VectorExtension(),
    ]