# Generated by Django 6.0.7 on 2026-07-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ragkit', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qaembedding',
            old_name='qa',
            new_name='QA_foreign_key',
        ),
    ]
